version: "3.8"

services:
  gateway:
    build: ./gateway
    depends_on:
      - api_v1
      - api_v2
    ports:
      - "8198:8198"
      - "8199:8199"
    restart: unless-stopped

  api_v1:
    build: ./service1
    depends_on:
      - service2
      - storage
    expose:
      - "8199"
    restart: unless-stopped
    environment:
      - API_VERSION=v1

  api_v2:
    build: ./service1
    depends_on:
      - service2
      - storage
    expose:
      - "8199"
    restart: unless-stopped
    environment:
      - API_VERSION=v2

  service2:
    build: ./service2
    depends_on:
      - storage
    expose:
      - "8300"
    restart: unless-stopped

  storage:
    build: ./storage
    volumes:
      - storage_data:/data
    expose:
      - "8200"
    restart: unless-stopped

  monitoring:
    build: ./monitoring
    container_name: monitoring
    ports:
      - "8400:8400"
    depends_on:
      - api_v1
      - service2
      - storage
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

volumes:
  storage_data: {}
